### ISSUE TITLE
Build RPM package

### ISSUE THREAD

**Issue by cha2lenger** [arthurdejong/nss-pam-ldapd#33]
Hi,
Could you please describe how can I build an PRM package for this project. While I can successfully do './configure | make | make install' for it, it is not clear how to get RPM package built for it. Could you please point me to the RPM spec file, etc. ?

Thank you.

**Comment by arthurdejong** [comment]
Hi Vladimir,

I don't ship distro-specific build scripts because I find they vary so much across distributions that it becomes hard to maintain and difficult to test. However some RPM-based distributions provide src RPMs that contain the spec files, e.g.:

- [CentOS 7](https://git.centos.org/tree/rpms!nss-pam-ldapd.git/c7)
- [Fedora](https://src.fedoraproject.org/rpms/nss-pam-ldapd/tree/master)
- [openSUSE](http://download.opensuse.org/source/distribution/leap/42.2/repo/oss/suse/src/nss-pam-ldapd-0.9.7-1.1.src.rpm.mirrorlist)
