### ISSUE TITLE
hang on centos 7

### ISSUE THREAD

**Issue by KlavsKlavsen** [arthurdejong/nss-pam-ldapd#5]
nslcd hangs at "random times" on some of our centos 7 boxes (several).. we mostly run centos 6 still (primarily due to this problem) - which means we cannot login, by other than root on console :(

When it hangs - systemd can't restart it either.. I have to kill it.

It's not much info.. but if there's any debug info I can setup - or something I can provide from it, the next time it hangs - then I'll gladly do so.

**Comment by arthurdejong** [comment]
Which version of nss-pam-ldapd are you using?

From version 0.9.0 you can configure debugging logging in nslcd.conf using the log option. Otherwise, you can start nslcd in debug mode (-d switch) to gather information.

Can you describe the state of the nslcd process when it "hangs"? Is the process still running? Can you provide the output from strace -p PIDOFNSLCD?

**Comment by KlavsKlavsen** [comment]
nss-pam-ldapd-0.8.13-8.el7.x86_64 

I'll provide the debug info, when it happens again.. :)

**Comment by arthurdejong** [comment]
Closing issue because of no response. Feel free to re-open the issue or create a new one if it is still relevant.
