### ISSUE TITLE
Passwords silently truncated

### ISSUE THREAD

**Issue by netbsdis** [arthurdejong/nss-pam-ldapd#52]
At my day job, one of our users complained that when they set the password to >= 128 characters length using our web interface, they could still login back to our web interface, but not login to our ssh gateway (which uses nslcd and pam).

That's a x86_64 debian (10) machine, in case this matters.

The  password store is a Windows AD accessed by ldap.

I could verify this - su and ssh fail (so it's not sshd per se,  but a lower layer) if the password is longer than 127 characters.

I think the reason is:

#define BUFLEN_PASSWORD     128  /* passwords */

in nss-pam-ldapd/nslcd/common.h

This should be increased, shouldn't it? At least to 256.

Regards
   -is

**Comment by arthurdejong** [comment]
I'm a bit reluctant to up the buffer length for passwords. Password hashes in AD are 128 bits which also seems to be a generally accepted amount of entropy to have in a password. That means passwords longer than 28 (random) lower case letters barely offer extra security (even shorter if more characters are used). If you are using passphrases of only the top 1000 English words you might end up with 70 or so characters.

According to https://docs.microsoft.com/en-us/windows-server/security/kerberos/passwords-technical-overview Windows generally limits password length to 127 characters (though internally it can deal with 256 character passwords) and a lot of other systems also don't allow such long passwords anyway (e.g. bcrypt implementations generally truncate passwords at 72 bytes and some other hashing implementations might also have issues with longer passwords).

To me having so long passwords is most likely a misunderstanding of the security properties of passwords rather than a real use case.

However, since it is such a trivial change and should have minimal other impact I made the change in 2fc652f.
